
services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: lab4_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_container
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:changeme@db/lab4_db
      - RELOAD=1

  adminer:
    image: adminer
    container_name: adminer_container
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  pgdata: