[tool.poetry]
name = "Ostapchuk"
version = "0.1.0"
packages = [{ include = "app" }]
description = ""
authors = ["you"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "*"
uvicorn = "*"
pydantic = "*"
pytest = "^9.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"